baseURL = 'https://duncanchiu409.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anatole'

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
## Sidebar settings
contentratio = 0.5
title = "I'm Tsz Wang Chiu"
author = "Tsz Wang Chiu"
description = "Call me Duncan 🤩"
profilePicture = "images/profile.png"
favicon = "favicons/"
customCss = ["css/custom.css", "css/syntax.css"]

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:duncanchiu409@gmail.com"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/duncanchiu409/"

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe=false